HTTP_METHOD_POST = 'POST'
HTTP_METHOD_GET = 'GET'
HTTP_METHOD_PATCH = 'PATCH'
HTTP_METHOD_DELETE = 'DELETE'
HTTP_METHOD_PUT = 'PUT'
HTTP_METHOD_OPTIONS = 'OPTIONS'

ALL_HTTP_METHODS = [
    HTTP_METHOD_POST,
    HTTP_METHOD_GET,
    HTTP_METHOD_PATCH,
    HTTP_METHOD_DELETE,
    HTTP_METHOD_PUT,
    HTTP_METHOD_OPTIONS,
]
